### ISSUE TITLE
Connection Page - Refactor 1.9.8 - Requirements

### ISSUE THREAD

**Issue by iljag00** [usepat/SW-soniccontrol#83]
## Connection Page

The connection page is the default starting page of SonicControl, so that the user can connect to a SonicAmp system. The user connects to the SonicAmp by choosing the port adress and pressing the connect button. After a connection was established, the firmware information of the SonicAmp is shown and the possibilty to disconnect is presented.

### Requirements

- [x] After the user starts SonicControl, the connection page is presented
- [x] The user can choose a adress and connect to it
- [x] After the connection attempt, the page shows the ongoing process (progressbar or animating three dots) #91
- [x] #94
  - [x] If a connection is possible, but the device itself is unkown, the user can activate the Serial Monitor to try and speak to the device
- [x] After a successfull connection was established, the firmware information about the SonicAmp is shown #93
- [x] During an established connection the user can disconnect. By the action of disconnection SonicControl goes into "Not connected"- mode #92
